# Generated by Django 4.2.3 on 2023-07-14 15:31

import SU_Transportation.freights.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoadCreateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pickup", models.CharField(max_length=100)),
                ("Delivery", models.CharField(max_length=100)),
                ("Commodity", models.CharField(max_length=100)),
                (
                    "Weight",
                    models.FloatField(
                        validators=[
                            SU_Transportation.freights.validators.positive_number
                        ]
                    ),
                ),
                ("Pickup_Date", models.DateField()),
                ("Pickup_Time", models.TimeField()),
                ("Delivery_Date", models.DateField()),
                ("Delivery_Time", models.TimeField()),
            ],
        ),
    ]
