# Generated by Django 4.2.3 on 2023-07-15 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("freights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loadcreatemodel",
            name="is_taken",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loadcreatemodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
