# Generated by Django 4.2.3 on 2023-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freights", "0003_alter_loadcreatemodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="loadcreatemodel",
            name="Delivery_Address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loadcreatemodel",
            name="Load_Number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="loadcreatemodel",
            name="Pickup_Address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
