# Generated by Django 4.2.3 on 2023-07-16 10:39

import SU_Transportation.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freights", "0004_loadcreatemodel_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadcreatemodel",
            name="Delivery_Address",
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name="loadcreatemodel",
            name="Load_Number",
            field=models.CharField(
                default=1,
                max_length=20,
                unique=True,
                validators=[SU_Transportation.accounts.validators.only_integers],
            ),
        ),
        migrations.AlterField(
            model_name="loadcreatemodel",
            name="Pickup_Address",
            field=models.TextField(default=1),
        ),
    ]
