# Generated by Django 4.2.3 on 2023-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freights", "0005_alter_loadcreatemodel_delivery_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loadcreatemodel",
            old_name="is_taken",
            new_name="is_completed",
        ),
        migrations.AddField(
            model_name="loadcreatemodel",
            name="Load_POD",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
        migrations.AlterField(
            model_name="loadcreatemodel",
            name="Delivery_Address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="loadcreatemodel",
            name="Pickup_Address",
            field=models.TextField(),
        ),
    ]
