# Generated by Django 4.2.3 on 2023-07-16 15:59

import SU_Transportation.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freights", "0006_rename_is_taken_loadcreatemodel_is_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadcreatemodel",
            name="Load_Number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[SU_Transportation.accounts.validators.only_integers],
            ),
        ),
        migrations.AlterField(
            model_name="loadcreatemodel",
            name="Load_POD",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents",
                validators=[SU_Transportation.accounts.validators.validate_file_size],
            ),
        ),
    ]
