# Generated by Django 4.2.3 on 2023-07-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactusmodel",
            name="is_red",
            field=models.BooleanField(default=False),
        ),
    ]
