# Generated by Django 4.2.3 on 2023-07-24 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_contactusmodel_is_red"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverapplication",
            name="Date_applied",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
