# Generated by Django 4.2.3 on 2023-07-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_driverapplication_date_applied"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driverapplication",
            old_name="Data_of_Birth",
            new_name="Date_of_Birth",
        ),
    ]
