# Generated by Django 4.2.3 on 2023-07-15 10:37

import SU_Transportation.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServicesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_picture",
                    models.ImageField(
                        upload_to="images",
                        validators=[
                            SU_Transportation.accounts.validators.validate_file_size
                        ],
                    ),
                ),
                ("service_name", models.CharField(max_length=50)),
                ("service_description", models.TextField()),
            ],
        ),
    ]
